# Stock Universe
NIFTY_50 = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "SBIN.NS", "BHARTIARTL.NS", "ITC.NS", "KOTAKBANK.NS",
    "LICI.NS", "LT.NS", "AXISBANK.NS", "ASIANPAINT.NS", "HCLTECH.NS",
    "MARUTI.NS", "TITAN.NS", "BAJFINANCE.NS", "SUNPHARMA.NS", "ULTRACEMCO.NS",
    "TATAMOTORS.NS", "NTPC.NS", "POWERGRID.NS", "M&M.NS", "ONGC.NS",
    "ADANIENT.NS", "ADANIPORTS.NS", "BAJAJFINSV.NS", "COALINDIA.NS", "JSWSTEEL.NS",
    "TATASTEEL.NS", "HINDALCO.NS", "GRASIM.NS", "CIPLA.NS", "TECHM.NS",
    "WIPRO.NS", "DRREDDY.NS", "SBILIFE.NS", "BRITANNIA.NS", "INDUSINDBK.NS",
    "TATACONSUM.NS", "DIVISLAB.NS", "EICHERMOT.NS", "NESTLEIND.NS", "BPCL.NS",
    "HEROMOTOCO.NS", "APOLLOHOSP.NS", "UPL.NS"
]

SENSEX_30 = [
    "RELIANCE.BO", "TCS.BO", "HDFCBANK.BO", "INFY.BO", "ICICIBANK.BO",
    "HINDUNILVR.BO", "SBIN.BO", "BHARTIARTL.BO", "ITC.BO", "KOTAKBANK.BO",
    "LT.BO", "AXISBANK.BO", "ASIANPAINT.BO", "HCLTECH.BO", "MARUTI.BO",
    "TITAN.BO", "BAJFINANCE.BO", "SUNPHARMA.BO", "ULTRACEMCO.BO", "TATAMOTORS.BO",
    "NTPC.BO", "POWERGRID.BO", "M&M.BO", "TATASTEEL.BO", "JSWSTEEL.BO",
    "BAJAJFINSV.BO", "INDUSINDBK.BO", "TECHM.BO", "WIPRO.BO", "NESTLEIND.BO"
]
